name: GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing the code to see if its ok."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: cd ${{ github.workspace }}
      - run: terraform init
      - run: terraform plan -var="my_access_key=${{secrets.MY_ACCESS_KEY}}" -var="my_secret_key=${{secrets.MY_SECRET_KEY}}"
      - run: terraform apply -var="my_access_key=${{secrets.MY_ACCESS_KEY}}" -var="my_secret_key=${{secrets.MY_SECRET_KEY}}"

      